PR #1559: Fix comparison of integer expressions of different signedness warning
Imported from GitHub PR https://github.com/abseil/abseil-cpp/pull/1559

```
//absl/hash/internal/hash.h:633:21: error: comparison of integer expressions of different signedness: 'int' and 'long unsigned int' [-Werror=sign-compare]
```

This warning is specific to the hashing of `std::bitset<>` on Big Endian platforms such as s390x

Merge 3f34d808c8689ffa47a798112ab44c0e3b32faa4 into 065d50d9f835cce8e4ee8f6d595518c409669901

Merging this change closes #1559

COPYBARA_INTEGRATE_REVIEW=https://github.com/abseil/abseil-cpp/pull/1559 from aligusnet:20211102.0-mongo 3f34d808c8689ffa47a798112ab44c0e3b32faa4
PiperOrigin-RevId: 578897545
Change-Id: Ifd1c947af3ad01e8e2a6241030ed29fb00842d53

(cherry picked from commit 7135ec61db16de640749194838e4337034451f8d)